### ISSUE TITLE
Validate HTML

### ISSUE THREAD

**Issue by DaanKorver** [beaupd/the-startup-game-of-tones#42]
Valideer de HTML voor de volgende routes:
https://the-startup-game-of-tones.vercel.app/onboarding
https://the-startup-game-of-tones.vercel.app/login
https://the-startup-game-of-tones.vercel.app/volume_1/chapter_1/subchapter_1
https://the-startup-game-of-tones.vercel.app/register

https://validator.w3.org/nu/?doc=https%3A%2F%2Fthe-startup-game-of-tones.vercel.app%2F

**Comment by NehaK275** [comment]
Hi @DaanKorver Can I solve this

**Comment by DaanKorver** [comment]
> Hi @DaanKorver Can I solve this

Yes you can! Create a pull request when you're done🅿️

**Comment by DaanKorver** [comment]
@NehaK275 Any progress on this?

**Comment by NehaK275** [comment]
I'm solving.
