### ISSUE TITLE
Gebruik geen ID's in CSS

### ISSUE THREAD

**Issue by DaanKorver** [beaupd/the-startup-game-of-tones#43]
https://github.com/beaupd/the-startup-game-of-tones/blob/f1b808d1174399fad75bf663bd6ced9c4d46b8a6/styles/LoginPage.module.css#L93

https://github.com/beaupd/the-startup-game-of-tones/blob/f1b808d1174399fad75bf663bd6ced9c4d46b8a6/styles/LoginPage.module.css#L101

https://github.com/beaupd/the-startup-game-of-tones/blob/f1b808d1174399fad75bf663bd6ced9c4d46b8a6/styles/LoginPage.module.css#L108

https://github.com/beaupd/the-startup-game-of-tones/blob/f1b808d1174399fad75bf663bd6ced9c4d46b8a6/styles/LoginPage.module.css#L109

https://github.com/beaupd/the-startup-game-of-tones/blob/f1b808d1174399fad75bf663bd6ced9c4d46b8a6/styles/LoginPage.module.css#L125

https://github.com/beaupd/the-startup-game-of-tones/blob/f1b808d1174399fad75bf663bd6ced9c4d46b8a6/styles/LoginPage.module.css#L142

https://github.com/beaupd/the-startup-game-of-tones/blob/f1b808d1174399fad75bf663bd6ced9c4d46b8a6/styles/LoginPage.module.css#L146

**Comment by beaupd** [comment]
In de nieuwe code gaan we hier opletten maar het is het niet waard om hier in de oude code alles aan te passen, gezien de tijd en de scope van het project.
