### ISSUE TITLE
Profile pagina

### ISSUE THREAD

**Issue by beaupd** [beaupd/the-startup-game-of-tones#7]
De pagina waarop je je eigen profiel/gebruiker informatie kan terug zien.

Prerequisite:

- [x]  Gebruiker authenticatie.
- [x] Database.
- [x] Design van pagina maken of regelen vanaf opdrachtgever.

**Comment by beaupd** [comment]
Handig als je de styling in modules op splitst per pagina zodat er geen conflicten tussen de pagina's en hun eigen styling zit.

**Comment by Finnvb** [comment]
De css styling heb ik in modules opgesplitst.
